title: Computing Wiki
description: Department of Statistics & Applied Probability Computing Wiki
theme: just-the-docs

url: https://ucsb-pstat.github.io/computing

aux_links:
  Back to PSTAT: https://www.pstat.ucsb.edu/resources/computing
  GitHub: https://github.com/ucsb-pstat/computing

nav_external_links:
  - title: Computing Wiki on GitHub
    url: https://github.com/ucsb-pstat/computing

favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/deptlogoblu.png"
color_scheme: ucsb

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: note
    color: blue
  highlight:
    color: yellow
  important:
    color: red