title: Computing Wiki
description: Department of Statistics & Applied Probability Computing Wiki
theme: just-the-docs

baseurl: "/computing-wiki"
url: "https://ucsb-pstat.github.io"

plugins:
  - jekyll-redirect-from

aux_links:
  Back to PSTAT: https://www.pstat.ucsb.edu/resources/computing
  GitHub: https://github.com/ucsb-pstat/computing-wiki

nav_external_links:
  - title: Computing Wiki on GitHub
    url: https://github.com/ucsb-pstat/computing-wiki

favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/deptlogoblu.png"
color_scheme: ucsb

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: note
    color: blue
  highlight:
    color: yellow
  important:
    color: red

# collections_dir: docs

# collections:
#   # Define a collection named "tests", its documents reside in the "_tests" directory
#   computing:
#     permalink: ":collection/:path/"
#     output: true

# just_the_docs:
#   # Define which collections are used in just-the-docs
#   collections:
#     # Reference the "tests" collection
#     computing:
#       # Give the collection a name
#       name: Computing Resources
#       # Exclude the collection from the navigation
#       # Supports true or false (default)
#       # nav_exclude: true
#       # Fold the collection in the navigation
#       # Supports true or false (default)
#       # nav_fold: true  # note: this option is new in v0.4
#       # Exclude the collection from the search
#       # Supports true or false (default)
#       # search_exclude: true
